# This workflow will build a MuleSoft project
name: Dev Pipeline
on:
  push:
    branches:
    - "dev"

jobs:
  build_deploy_dev:
    if: "github.ref == 'refs/heads/dev' && !contains(github.event.head_commit.message, 'Merge branch')"
    #runs-on: [mule-runner]
    runs-on: [mulesoft-k8s-runners]
    env:
      ClientId: ${{ secrets.DEV_CLIENTID }}
      ClientSecret: ${{ secrets.DEV_CLIENTSECRET }}
      DEPLOY_ENV: "Development"
      TARGET_NAME: "mulesoft-anypoint-dev"
      PUBLIC_URL: ".corp.hpicloud.net"
      CPU_RES: "100m"
      CPU_LIMIT: "1500m"
      MEM_RES: "1000Mi"
      MEM_LIMIT: "2000Mi"
      VER_INCR: "DEV"
      REPL_COUNT: "1"
      ENFORCE_DEPLOY: "true"
      PERSIST_OBJSTORE: "true"
      PROP_ENV: "dev"

    steps:
    - uses: actions/checkout@v2
    - name: Increment version number in pom file.
      run: |
        #sleep 30
        current_version=$(sed -n '7s/.*<version>\([^<]*\)<\/version>.*/\1/p' pom.xml)
        new_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        env_ver=$(echo "$new_version"-"$VER_INCR")
        sed -i "7s/<version>.*<\/version>/<version>${env_ver}<\/version>/" pom.xml
        echo $env_ver
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -m "Auto-increment version number to ${env_ver}" pom.xml
        git push
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: MVN Build
      run: |
        #mvn -B package -X --file pom.xml
        mvn -B package --file pom.xml
    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/.$commitHash.jar/g")
        mv $artifactName1 $artifactName2
    - uses: actions/upload-artifact@master
      with:
          name: artifacts
          path: target/*.jar
    - uses: actions/download-artifact@master
      with:
        name: artifacts
    - name: Deploy to Exchange
      run: |
       sudo cp settings.xml $HOME/.m2/settings.xml       
       mvn -v
       mvn --version
       mvn clean deploy
    - name: Publish to Anypoint Platform
      run: |
       mvn deploy -Denv=$PROP_ENV -DmuleDeploy
